-- Migration 003: Example seed data for local dev and smoke testing
-- Run ONLY in local/staging environments — NOT in production.
-- Uses fake emails; adjust to real names/emails before the 2026 season.
--
-- Usage: paste into Supabase SQL Editor (local dev instance only)

-- ── Sample players ─────────────────────────────────────────────────────────
-- Tokens are fake UUIDs for dev; real tokens are 48-char hex generated by the app.

insert into players (id, name, email, magic_token, paid_buyin, starting_points) values
  ('00000000-0001-0000-0000-000000000001', 'Ryan (Commish)', 'ryangerda@gmail.com',       'dev-token-ryan',    true,  25000),
  ('00000000-0001-0000-0000-000000000002', 'Ben',            'ben@example.com',            'dev-token-ben',     true,  25000),
  ('00000000-0001-0000-0000-000000000003', 'Josh',           'josh@example.com',           'dev-token-josh',    true,  25000),
  ('00000000-0001-0000-0000-000000000004', 'Andrew',         'andrew@example.com',         'dev-token-andrew',  false, 25000),
  ('00000000-0001-0000-0000-000000000005', 'Austin',         'austin@example.com',         'dev-token-austin',  true,  25000)
on conflict (id) do nothing;


-- ── Sample week 1 games (2026) ─────────────────────────────────────────────
-- Spreads are made-up; replace with real lines from The Odds API before week 1.

insert into games (id, season, week, espn_event_id, home_team, away_team, favorite_team, underdog_team, spread, kickoff_at, status) values
  ('00000000-0002-0000-0000-000000000001', 2026, 1, 'espn-001',
   'Kansas City Chiefs', 'Baltimore Ravens',
   'Kansas City Chiefs', 'Baltimore Ravens', 3.5,
   '2026-09-10 20:20:00+00', 'scheduled'),

  ('00000000-0002-0000-0000-000000000002', 2026, 1, 'espn-002',
   'Philadelphia Eagles', 'Dallas Cowboys',
   'Philadelphia Eagles', 'Dallas Cowboys', 6.5,
   '2026-09-13 17:00:00+00', 'scheduled'),

  ('00000000-0002-0000-0000-000000000003', 2026, 1, 'espn-003',
   'San Francisco 49ers', 'Seattle Seahawks',
   'San Francisco 49ers', 'Seattle Seahawks', 4.0,
   '2026-09-13 17:00:00+00', 'scheduled'),

  ('00000000-0002-0000-0000-000000000004', 2026, 1, 'espn-004',
   'Buffalo Bills', 'Miami Dolphins',
   'Buffalo Bills', 'Miami Dolphins', 7.0,
   '2026-09-13 20:25:00+00', 'scheduled'),

  ('00000000-0002-0000-0000-000000000005', 2026, 1, 'espn-005',
   'Detroit Lions', 'Los Angeles Rams',
   'Detroit Lions', 'Los Angeles Rams', 2.5,
   '2026-09-14 20:20:00+00', 'scheduled')
on conflict (season, week, espn_event_id) do nothing;


-- ── Week 1 week_log rows (starting balances) ───────────────────────────────

insert into week_log (player_id, season, week, start_points) values
  ('00000000-0001-0000-0000-000000000001', 2026, 1, 25000),
  ('00000000-0001-0000-0000-000000000002', 2026, 1, 25000),
  ('00000000-0001-0000-0000-000000000003', 2026, 1, 25000),
  ('00000000-0001-0000-0000-000000000004', 2026, 1, 25000),
  ('00000000-0001-0000-0000-000000000005', 2026, 1, 25000)
on conflict (player_id, season, week) do nothing;


-- ── Sample picks for smoke testing ────────────────────────────────────────
-- These test the validation: total = 10,500 ≤ 25,000 ✓ all multiples of 500 ✓

insert into picks (player_id, game_id, pick_side, pick_amount) values
  -- Ryan: 3 picks
  ('00000000-0001-0000-0000-000000000001', '00000000-0002-0000-0000-000000000001', 'FAVORITE', 5000),
  ('00000000-0001-0000-0000-000000000001', '00000000-0002-0000-0000-000000000002', 'UNDERDOG', 3000),
  ('00000000-0001-0000-0000-000000000001', '00000000-0002-0000-0000-000000000003', 'FAVORITE', 2500),
  -- Ben: 1 pick (all-in on KC)
  ('00000000-0001-0000-0000-000000000002', '00000000-0002-0000-0000-000000000001', 'FAVORITE', 25000),
  -- Josh: 2 picks
  ('00000000-0001-0000-0000-000000000003', '00000000-0002-0000-0000-000000000002', 'FAVORITE', 8000),
  ('00000000-0001-0000-0000-000000000003', '00000000-0002-0000-0000-000000000004', 'UNDERDOG', 4000)
  -- Andrew: no picks (will get -5,000 penalty)
  -- Austin: no picks (will get -5,000 penalty)
on conflict (player_id, game_id) do nothing;


-- ── Verify the seed ────────────────────────────────────────────────────────
-- Run these SELECTs to confirm everything looks right:

-- select name, magic_token, paid_buyin from players order by name;
-- select home_team, away_team, spread, kickoff_at, status from games where season=2026 order by kickoff_at;
-- select p.name, g.home_team, g.away_team, pk.pick_side, pk.pick_amount
--   from picks pk join players p on p.id=pk.player_id join games g on g.id=pk.game_id
--   order by p.name;
-- select p.name, wl.week, wl.start_points from week_log wl join players p on p.id=wl.player_id;
